"""Generate the four auto-generated reference pages for the MkDocs site.

Usage:
    python scripts/gen_docs.py             # write the pages
    python scripts/gen_docs.py --check     # exit 1 if working tree differs
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import yaml
from pydantic.fields import FieldInfo

from nsc.builder.build import build_command_model
from nsc.config.models import Config, Defaults, Profile
from nsc.model.command_model import Operation, Resource
from nsc.output.errors import EXIT_CODES, ErrorType
from nsc.schema.loader import load_schema

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_REFERENCE_DIR = REPO_ROOT / "docs" / "reference"
BUNDLED_MANIFEST = REPO_ROOT / "nsc" / "schemas" / "bundled" / "manifest.yaml"
BUNDLED_DIR = REPO_ROOT / "nsc" / "schemas" / "bundled"

_HEADER_NOTE = (
    "<!-- This file is auto-generated by `scripts/gen_docs.py`. "
    "Do not edit by hand — re-run the generator instead. -->"
)

# Maps slot name → display verb (Operation has no .verb field; the verb is
# implicit in which slot of Resource the operation occupies).
_SLOT_VERBS: tuple[tuple[str, str], ...] = (
    ("list_op", "list"),
    ("get_op", "get"),
    ("create_op", "create"),
    ("update_op", "update"),
    ("replace_op", "replace"),
    ("delete_op", "delete"),
)


def _latest_bundled_schema_path() -> Path:
    manifest = yaml.safe_load(BUNDLED_MANIFEST.read_text())
    entry = manifest["schemas"][-1]
    return BUNDLED_DIR / str(entry["file"])


def _verb_from_operation_id(operation_id: str) -> str:
    """Derive a display verb from a custom-action operation_id.

    Operation IDs for custom actions follow the pattern
    ``<tag>_<resource>_<action>_<http-verb>`` (e.g.
    ``dcim_cables_terminate_create``).  We strip the known suffixes
    (``_retrieve``, ``_list``, ``_create``, ``_partial_update``,
    ``_update``, ``_destroy``) and return the remainder as the verb.
    The last underscore-separated token serves as a readable fallback.
    """
    suffixes_to_strip = (
        "_retrieve",
        "_list",
        "_create",
        "_partial_update",
        "_update",
        "_destroy",
    )
    stem = operation_id
    for suffix in suffixes_to_strip:
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    # The last token of what remains is the action name.
    return stem.split("_")[-1] if stem else operation_id


def _resource_operations(resource: Resource) -> list[tuple[str, Operation]]:
    """Return ``(verb, operation)`` pairs in stable order.

    Standard CRUD slots come first in a fixed order; custom actions follow
    sorted by their operation_id so output is deterministic.
    """
    result: list[tuple[str, Operation]] = []
    for slot, verb in _SLOT_VERBS:
        op: Operation | None = getattr(resource, slot)
        if op is not None:
            result.append((verb, op))
    for op in sorted(resource.custom_actions, key=lambda o: o.operation_id):
        result.append((_verb_from_operation_id(op.operation_id), op))
    return result


def render_cli() -> str:
    """Render the CLI reference page from the latest bundled schema."""
    schema_path = _latest_bundled_schema_path()
    loaded = load_schema(str(schema_path))
    model = build_command_model(loaded)

    lines: list[str] = [
        "# CLI reference",
        "",
        _HEADER_NOTE,
        "",
        f"Generated from `{schema_path.name}` (NetBox `{loaded.document.info.version}`).",
        "",
        "Every endpoint exposed by NetBox surfaces as `nsc <tag> <resource> <verb>`.",
        "Verbs are derived from the `operationId`: `list`, `get`, `create`, `update`,"
        " `replace`, `delete`,",
        "plus custom actions (e.g., `available-ips`).",
        "",
    ]
    for tag_name in sorted(model.tags):
        tag = model.tags[tag_name]
        lines.append(f"## {tag_name}")
        lines.append("")
        for resource_name in sorted(tag.resources):
            resource = tag.resources[resource_name]
            lines.append(f"### {tag_name} {resource_name}")
            lines.append("")
            for verb, op in _resource_operations(resource):
                lines.append(
                    f"- **`nsc {tag_name} {resource_name} {verb}`** — "
                    f"`{op.http_method.value} {op.path}`"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _format_type(annotation: Any) -> str:
    s = str(annotation)
    return s.replace("typing.", "").replace("nsc.config.models.", "")


def _format_default(info: FieldInfo) -> str:
    if info.is_required():
        return "_(required)_"
    default = info.get_default(call_default_factory=True)
    if default is None:
        return "`None`"
    if isinstance(default, dict):
        return "`{}`" if not default else f"`{default!r}`"
    if isinstance(default, list):
        return "`[]`" if not default else f"`{default!r}`"
    return f"`{default!r}`"


def render_config() -> str:
    """Render the configuration reference page from Pydantic model introspection."""
    lines: list[str] = [
        "# Configuration reference",
        "",
        _HEADER_NOTE,
        "",
        "Generated from the Pydantic models in `nsc/config/models.py`.",
        "All fields below describe `~/.nsc/config.yaml`.",
        "",
    ]
    for model_cls in (Config, Profile, Defaults):
        lines.append(f"## `{model_cls.__name__}`")
        lines.append("")
        if model_cls.__doc__:
            lines.append(model_cls.__doc__.strip())
            lines.append("")
        lines.append("| Field | Type | Default |")
        lines.append("|---|---|---|")
        for name, info in model_cls.model_fields.items():
            type_str = _format_type(info.annotation)
            default_str = _format_default(info)
            lines.append(f"| `{name}` | `{type_str}` | {default_str} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_schemas() -> str:
    """Render the bundled schemas reference page from the manifest."""
    manifest = yaml.safe_load(BUNDLED_MANIFEST.read_text())
    lines: list[str] = [
        "# Bundled schemas",
        "",
        _HEADER_NOTE,
        "",
        "These NetBox OpenAPI snapshots ship inside the wheel and serve as the offline",
        "fallback when a live schema can't be fetched and no per-profile cache exists.",
        "",
        "| Version | File |",
        "|---|---|",
    ]
    for entry in manifest["schemas"]:
        lines.append(f"| `{entry['version']}` | `{entry['file']}` |")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_exit_codes() -> str:
    """Render the exit codes reference page from EXIT_CODES and ErrorType."""
    by_code: dict[int, list[ErrorType]] = {}
    for et, code in EXIT_CODES.items():
        by_code.setdefault(code, []).append(et)

    lines: list[str] = [
        "# Exit codes",
        "",
        _HEADER_NOTE,
        "",
        "`nsc` returns one of the exit codes below. Multiple `ErrorType` values may share",
        "an exit code; the discriminant is the envelope `type` field, not the code.",
        "",
        "| Exit code | `type` values |",
        "|---|---|",
    ]
    for code in sorted(by_code):
        types = ", ".join(f"`{et.value}`" for et in sorted(by_code[code], key=lambda e: e.value))
        lines.append(f"| `{code}` | {types} |")
    lines.append("")
    lines.append(
        "Exit code `0` is reserved for success. Exit code `1` is the catch-all internal-error."
    )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_PAGES: dict[str, Callable[[], str]] = {
    "cli.md": render_cli,
    "config.md": render_config,
    "schemas.md": render_schemas,
    "exit-codes.md": render_exit_codes,
}


def main(*, check: bool = False) -> int:
    """Generate (or check) all four reference pages. Returns an exit code."""
    DOCS_REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    drifted: list[str] = []
    for filename, render in _PAGES.items():
        target = DOCS_REFERENCE_DIR / filename
        new_content = render()
        if check:
            old_content = target.read_text() if target.exists() else ""
            if old_content != new_content:
                drifted.append(filename)
        else:
            target.write_text(new_content)
    if check and drifted:
        print(
            f"reference pages drifted (re-run `python scripts/gen_docs.py`): {drifted}",
            file=sys.stderr,
        )
        return 1
    return 0


def _cli() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any generated page differs from the working tree.",
    )
    args = parser.parse_args()
    return main(check=args.check)


if __name__ == "__main__":
    sys.exit(_cli())
