"""Generate AGENTS.md from CLAUDE.md.

CLAUDE.md is the source of truth; AGENTS.md is a vendor-neutral mirror
consumed by agent harnesses that look for that filename (Codex, Cursor,
aider, …). Run this script when CLAUDE.md changes; CI runs it with
--check to fail the PR if AGENTS.md drifted.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / "CLAUDE.md"
DEST = REPO_ROOT / "AGENTS.md"

# Cap the --check unified diff so a full-file rewrite doesn't flood CI logs.
_DIFF_LINE_CAP = 40

_HEADER = """\
<!--
  AGENTS.md is auto-generated from CLAUDE.md by scripts/sync_agents_md.py.
  Do NOT edit this file directly — edit CLAUDE.md and run
  `uv run python scripts/sync_agents_md.py` to regenerate. CI fails the PR
  if this file drifts from CLAUDE.md (see .github/workflows/lint.yml).
-->

"""


def render() -> str:
    source_text = SOURCE.read_text(encoding="utf-8")
    return _HEADER + source_text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail with non-zero exit if AGENTS.md does not match the generated output.",
    )
    parser.add_argument(
        "--no-diff",
        action="store_true",
        help="On --check drift, print only the summary line (no unified diff).",
    )
    args = parser.parse_args(argv)

    rendered = render()

    script_path = Path(__file__).resolve().relative_to(REPO_ROOT)

    if args.check:
        if not DEST.exists():
            print(
                f"AGENTS.md is missing; run `uv run python {script_path}`.",
                file=sys.stderr,
            )
            return 1
        existing = DEST.read_text(encoding="utf-8")
        if existing != rendered:
            if not args.no_diff:
                # Cap the diff (parity with scripts/gen_docs.py) so a full-file
                # rewrite doesn't flood the CI log; the suppressed count is shown.
                diff = list(
                    difflib.unified_diff(
                        existing.splitlines(keepends=True),
                        rendered.splitlines(keepends=True),
                        fromfile="AGENTS.md (on disk)",
                        tofile="AGENTS.md (expected)",
                    )
                )
                sys.stderr.writelines(diff[:_DIFF_LINE_CAP])
                if len(diff) > _DIFF_LINE_CAP:
                    print(
                        f"... {len(diff) - _DIFF_LINE_CAP} more diff lines suppressed",
                        file=sys.stderr,
                    )
                print(file=sys.stderr)
            print(
                f"AGENTS.md is out of date; run `uv run python {script_path}` "
                "and commit the result.",
                file=sys.stderr,
            )
            return 1
        return 0

    DEST.write_text(rendered, encoding="utf-8")
    print(f"Wrote {DEST.relative_to(REPO_ROOT)} ({len(rendered)} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
